services:
  systema:
    build:
      context: ./src/SystemA
    ports:
      - "5001:8080"

  systemb:
    build:
      context: ./src/SystemB
    ports:
      - "5002:8080"

  mergeservice:
    build:
      context: ./src/MergeService
    ports:
      - "5181:8080"
    depends_on:
      - systema
      - systemb
    environment:
      - SystemA__BaseUrl=http://systema:8080
      - SystemB__BaseUrl=http://systemb:8080